name: Tests

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test-libs:
      name: Test libraries
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test:libs

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Libraries Test Report
          path: test-libs.json
          reporter: mocha-json